
export const SET_USER = "SET_USER";

export const FETCH_LOGIN = "FETCH_LOGIN";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";
export const FETCH_LOGIN_CLEAR = "FETCH_LOGIN_CLEAR";

export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";
export const FETCH_CUSTOMERS_FAILURE = "FETCH_CUSTOMERS_FAILURE";

export const FETCH_STAFFS = "FETCH_STAFFS";
export const FETCH_STAFFS_SUCCESS = "FETCH_STAFFS_SUCCESS";
export const FETCH_STAFFS_FAILURE = "FETCH_STAFFS_FAILURE";

export const FETCH_ADMINS = "FETCH_ADMINS";
export const FETCH_ADMINS_SUCCESS = "FETCH_ADMINS_SUCCESS";
export const FETCH_ADMINS_FAILURE = "FETCH_ADMINS_FAILURE";

export const FETCH_USER_DETAIL = "FETCH_USER_DETAIL";
export const FETCH_USER_DETAIL_SUCCESS = "FETCH_USER_DETAIL_SUCCESS";
export const FETCH_USER_DETAIL_FAILURE = "FETCH_USER_DETAIL_FAILURE";

export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_FAILURE = "CREATE_CUSTOMER_FAILURE";

export const CREATE_STAFF = "CREATE_STAFF";
export const CREATE_STAFF_SUCCESS = "CREATE_STAFF_SUCCESS";
export const CREATE_STAFF_FAILURE = "CREATE_STAFF_FAILURE";

export const CREATE_ADMIN = "CREATE_ADMIN";
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";
export const CREATE_ADMIN_FAILURE = "CREATE_ADMIN_FAILURE";

export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILURE = "UPDATE_CUSTOMER_FAILURE";

export const UPDATE_STAFF = "UPDATE_STAFF";
export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS";
export const UPDATE_STAFF_FAILURE = "UPDATE_STAFF_FAILURE";

export const UPDATE_ADMIN = "UPDATE_ADMIN";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_FAILURE = "UPDATE_ADMIN_FAILURE";

export const DEACTIVATE_USER = "DEACTIVATE_USER";
export const DEACTIVATE_USER_SUCCESS = "DEACTIVATE_USER_SUCCESS";
export const DEACTIVATE_USER_FAILURE = "DEACTIVATE_USER_FAILURE";

export const ACTIVATE_USER = "ACTIVATE_USER";
export const ACTIVATE_USER_SUCCESS = "ACTIVATE_USER_SUCCESS";
export const ACTIVATE_USER_FAILURE = "ACTIVATE_USER_FAILURE";

export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE";

export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";
export const FETCH_COURSE_DETAIL_SUCCESS = "FETCH_COURSE_DETAIL_SUCCESS";
export const FETCH_COURSE_DETAIL_FAILURE = "FETCH_COURSE_DETAIL_FAILURE";
export const CLEAR_COURSE_DETAIL = "CLEAR_COURSE_DETAIL";

export const ADD_COURSE = "ADD_COURSE";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";

export const UPDATE_COURSE = "UPDATE_COURSE";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAILURE = "UPDATE_COURSE_FAILURE";

export const DEACTIVATE_COURSE = "DEACTIVATE_COURSE";
export const DEACTIVATE_COURSE_SUCCESS = "DEACTIVATE_COURSE_SUCCESS";
export const DEACTIVATE_COURSE_FAILURE = "DEACTIVATE_COURSE_FAILURE";

export const ACTIVATE_COURSE = "ACTIVATE_COURSE";
export const ACTIVATE_COURSE_SUCCESS = "ACTIVATE_COURSE_SUCCESS";
export const ACTIVATE_COURSE_FAILURE = "ACTIVATE_COURSE_FAILURE";

export const FETCH_MODULES = "FETCH_MODULES";
export const FETCH_MODULES_SUCCESS = "FETCH_MODULES_SUCCESS";
export const FETCH_MODULES_FAILURE = "FETCH_MODULES_FAILURE";
export const FETCH_MODULES_RESET = "FETCH_MODULES_RESET";

export const UPDATE_MODULE = "UPDATE_MODULE";
export const UPDATE_MODULE_SUCCESS = "UPDATE_MODULE_SUCCESS";
export const UPDATE_MODULE_FAILURE = "UPDATE_MODULE_FAILURE";

export const ADD_MODULE = "ADD_MODULE";
export const ADD_MODULE_SUCCESS = "ADD_MODULE_SUCCESS";
export const ADD_MODULE_FAILURE = "ADD_MODULE_FAILURE";

export const DEACTIVATE_MODULE = "DEACTIVATE_MODULE";
export const DEACTIVATE_MODULE_SUCCESS = "DEACTIVATE_MODULE_SUCCESS";
export const DEACTIVATE_MODULE_FAILURE = "DEACTIVATE_MODULE_FAILURE";

export const ACTIVATE_MODULE = "ACTIVATE_MODULE";
export const ACTIVATE_MODULE_SUCCESS = "ACTIVATE_MODULE_SUCCESS";
export const ACTIVATE_MODULE_FAILURE = "ACTIVATE_MODULE_FAILURE";

export const FETCH_LESSON = "FETCH_LESSON";
export const FETCH_LESSON_SUCCESS = "FETCH_LESSON_SUCCESS";
export const FETCH_LESSON_FAILURE = "FETCH_LESSON_FAILURE";

export const UPDATE_LESSON = "UPDATE_LESSON";
export const UPDATE_LESSON_SUCCESS = "UPDATE_LESSON_SUCCESS";
export const UPDATE_LESSON_FAILURE = "UPDATE_LESSON_FAILURE";

export const ADD_LESSON = "ADD_LESSON";
export const ADD_LESSON_SUCCESS = "ADD_LESSON_SUCCESS";
export const ADD_LESSON_FAILURE = "ADD_LESSON_FAILURE";

export const DEACTIVATE_LESSON = "DEACTIVATE_LESSON";
export const DEACTIVATE_LESSON_SUCCESS = "DEACTIVATE_LESSON_SUCCESS";
export const DEACTIVATE_LESSON_FAILURE = "DEACTIVATE_LESSON_FAILURE";

export const ACTIVATE_LESSON = "ACTIVATE_LESSON";
export const ACTIVATE_LESSON_SUCCESS = "ACTIVATE_LESSON_SUCCESS";
export const ACTIVATE_LESSON_FAILURE = "ACTIVATE_LESSON_FAILURE";

export const ADD_COURSE_CRITERIA = "ADD_COURSE_CRITERIA";
export const ADD_COURSE_CRITERIA_SUCCESS = "ADD_COURSE_CRITERIA_SUCCESS";
export const ADD_COURSE_CRITERIA_FAILURE = "ADD_COURSE_CRITERIA_FAILURE";

export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAILURE = "FETCH_LOCATIONS_FAILURE";

export const FETCH_LOCATION_DETAIL = "FETCH_LOCATION_DETAIL";
export const FETCH_LOCATION_DETAIL_SUCCESS = "FETCH_LOCATION_DETAIL_SUCCESS";
export const FETCH_LOCATION_DETAIL_FAILURE = "FETCH_LOCATION_DETAIL_FAILURE";

export const ADD_LOCATION = "ADD_LOCATION";
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_FAILURE = "ADD_LOCATION_FAILURE";

export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAILURE = "UPDATE_LOCATION_FAILURE";

export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS";
export const FETCH_DEPARTMENTS_SUCCESS = "FETCH_DEPARTMENTS_SUCCESS";
export const FETCH_DEPARTMENTS_FAILURE = "FETCH_DEPARTMENTS_FAILURE";

export const FETCH_DEPARTMENT_DETAIL = "FETCH_DEPARTMENT_DETAIL";
export const FETCH_DEPARTMENT_DETAIL_SUCCESS = "FETCH_DEPARTMENT_DETAIL_SUCCESS";
export const FETCH_DEPARTMENT_DETAIL_FAILURE = "FETCH_DEPARTMENT_DETAIL_FAILURE";

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_FAILURE = "UPDATE_DEPARTMENT_FAILURE";

export const FETCH_BRANCHES = "FETCH_BRANCHES";
export const FETCH_BRANCHES_SUCCESS = "FETCH_BRANCHES_SUCCESS";
export const FETCH_BRANCHES_FAILURE = "FETCH_BRANCHES_FAILURE";

export const FETCH_BRANCH_DETAIL = "FETCH_BRANCH_DETAIL";
export const FETCH_BRANCH_DETAIL_SUCCESS = "FETCH_BRANCH_DETAIL_SUCCESS";
export const FETCH_BRANCH_DETAIL_FAILURE = "FETCH_BRANCH_DETAIL_FAILURE";

export const ADD_BRANCH = "ADD_BRANCH";
export const ADD_BRANCH_SUCCESS = "ADD_BRANCH_SUCCESS";
export const ADD_BRANCH_FAILURE = "ADD_BRANCH_FAILURE";

export const UPDATE_BRANCH = "UPDATE_BRANCH";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_FAILURE = "UPDATE_BRANCH_FAILURE";

export const FETCH_DESIGNATIONS = "FETCH_DESIGNATIONS";
export const FETCH_DESIGNATIONS_SUCCESS = "FETCH_DESIGNATIONS_SUCCESS";
export const FETCH_DESIGNATIONS_FAILURE = "FETCH_DESIGNATIONS_FAILURE";

export const FETCH_DESIGNATION_DETAIL = "FETCH_DESIGNATION_DETAIL";
export const FETCH_DESIGNATION_DETAIL_SUCCESS = "FETCH_DESIGNATION_DETAIL_SUCCESS";
export const FETCH_DESIGNATION_DETAIL_FAILURE = "FETCH_DESIGNATION_DETAIL_FAILURE";

export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAILURE = "ADD_DESIGNATION_FAILURE";

export const UPDATE_DESIGNATION = "UPDATE_DESIGNATION";
export const UPDATE_DESIGNATION_SUCCESS = "UPDATE_DESIGNATION_SUCCESS";
export const UPDATE_DESIGNATION_FAILURE = "UPDATE_DESIGNATION_FAILURE";

export const FETCH_CENTRES = "FETCH_CENTRES";
export const FETCH_CENTRES_SUCCESS = "FETCH_CENTRES_SUCCESS";
export const FETCH_CENTRES_FAILURE = "FETCH_CENTRES_FAILURE";

export const FETCH_CENTRE_DETAIL = "FETCH_CENTRE_DETAIL";
export const FETCH_CENTRE_DETAIL_SUCCESS = "FETCH_CENTRE_DETAIL_SUCCESS";
export const FETCH_CENTRE_DETAIL_FAILURE = "FETCH_CENTRE_DETAIL_FAILURE";

export const ADD_CENTRE = "ADD_CENTRE";
export const ADD_CENTRE_SUCCESS = "ADD_CENTRE_SUCCESS";
export const ADD_CENTRE_FAILURE = "ADD_CENTRE_FAILURE";

export const UPDATE_CENTRE = "UPDATE_CENTRE";
export const UPDATE_CENTRE_SUCCESS = "UPDATE_CENTRE_SUCCESS";
export const UPDATE_CENTRE_FAILURE = "UPDATE_CENTRE_FAILURE";

export const FETCH_GROUPS = "FETCH_GROUPS";
export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_GROUPS_FAILURE = "FETCH_GROUPS_FAILURE";

export const FETCH_GROUP_DETAIL = "FETCH_GROUP_DETAIL";
export const FETCH_GROUP_DETAIL_SUCCESS = "FETCH_GROUP_DETAIL_SUCCESS";
export const FETCH_GROUP_DETAIL_FAILURE = "FETCH_GROUP_DETAIL_FAILURE";

export const ADD_GROUP = "ADD_GROUP";
export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS";
export const ADD_GROUP_FAILURE = "ADD_GROUP_FAILURE";

export const UPDATE_GROUP = "UPDATE_GROUP";
export const UPDATE_GROUP_SUCCESS = "UPDATE_GROUP_SUCCESS";
export const UPDATE_GROUP_FAILURE = "UPDATE_GROUP_FAILURE";

export const FETCH_ANALYTICS = "FETCH_ANALYTICS";
export const FETCH_ANALYTICS_SUCCESS = "FETCH_ANALYTICS_SUCCESS";
export const FETCH_ANALYTICS_FAILURE = "FETCH_ANALYTICS_FAILURE";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";
export const FORGOT_PASSWORD_CLEAR = "FORGOT_PASSWORD_CLEAR";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
export const RESET_PASSWORD_CLEAR = "RESET_PASSWORD_CLEAR";

export const FETCH_COURSE_PROGRESS_LIST_BY_USER_ID = "FETCH_COURSE_PROGRESS_LIST_BY_USER_ID";
export const FETCH_COURSE_PROGRESS_LIST_BY_USER_ID_SUCCESS = "FETCH_COURSE_PROGRESS_LIST_BY_USER_ID_SUCCESS";
export const FETCH_COURSE_PROGRESS_LIST_BY_USER_ID_FAILURE = "FETCH_COURSE_PROGRESS_LIST_BY_USER_ID_FAILURE";

export const FETCH_USER_PROGRESS_LIST_BY_COURSE_ID = "FETCH_USER_PROGRESS_LIST_BY_COURSE_ID";
export const FETCH_USER_PROGRESS_LIST_BY_COURSE_ID_SUCCESS = "FETCH_USER_PROGRESS_LIST_BY_COURSE_ID_SUCCESS";
export const FETCH_USER_PROGRESS_LIST_BY_COURSE_ID_FAILURE = "FETCH_USER_PROGRESS_LIST_BY_COURSE_ID_FAILURE";

export const FETCH_COURSE_PROGRESS_DETAIL = "FETCH_COURSE_PROGRESS_DETAIL";
export const FETCH_COURSE_PROGRESS_DETAIL_SUCCESS = "FETCH_COURSE_PROGRESS_DETAIL_SUCCESS";
export const FETCH_COURSE_PROGRESS_DETAIL_FAILURE = "FETCH_COURSE_PROGRESS_DETAIL_FAILURE";

export const SAVE_ACTIVITY = "SAVE_ACTIVITY";
export const SAVE_ACTIVITY_SUCCESS = "SAVE_ACTIVITY_SUCCESS";
export const SAVE_ACTIVITY_FAILURE = "SAVE_ACTIVITY_FAILURE";
export const SAVE_ACTIVITY_CLEAR = "SAVE_ACTIVITY_CLEAR";

export const FETCH_LESSON_ACTIVITY = "FETCH_LESSON_ACTIVITY";
export const FETCH_LESSON_ACTIVITY_SUCCESS = "FETCH_LESSON_ACTIVITY_SUCCESS";
export const FETCH_LESSON_ACTIVITY_FAILURE = "FETCH_LESSON_ACTIVITY_FAILURE";
export const FETCH_LESSON_ACTIVITY_CLEAR = "FETCH_LESSON_ACTIVITY_CLEAR";

export const CREATE_WEBINAR = "CREATE_WEBINAR";
export const CREATE_WEBINAR_SUCCESS = "CREATE_WEBINAR_SUCCESS";
export const CREATE_WEBINAR_FAILURE = "CREATE_WEBINAR_FAILURE";
export const CLEAR_CREATE_WEBINAR = "CLEAR_CREATE_WEBINAR"

export const FETCH_WEBINARS = "FETCH_WEBINARS";
export const FETCH_WEBINARS_SUCCESS = "FETCH_WEBINARS_SUCCESS";
export const FETCH_WEBINARS_FAILURE = "FETCH_WEBINARS_FAILURE";

export const FETCH_WEBINAR_DETAIL = "FETCH_WEBINAR_DETAIL";
export const FETCH_WEBINAR_DETAIL_SUCCESS = "FETCH_WEBINAR_DETAIL_SUCCESS";
export const FETCH_WEBINAR_DETAIL_FAILURE = "FETCH_WEBINAR_DETAIL_FAILURE";
export const CLEAR_WEBINAR_DETAIL = "CLEAR_WEBINAR_DETAIL";

export const UPDATE_WEBINAR = "UPDATE_WEBINAR";
export const UPDATE_WEBINAR_SUCCESS = "UPDATE_WEBINAR_SUCCESS";
export const UPDATE_WEBINAR_FAILURE = "UPDATE_WEBINAR_FAILURE";
export const CLEAR_UPDATE_WEBINAR = "CLEAR_UPDATE_WEBINAR"

export const DISABLE_WEBINAR = "DELETE_WEBINAR";
export const DISABLE_WEBINAR_SUCCESS = "DELETE_WEBINAR_SUCCESS";
export const DISABLE_WEBINAR_FAILURE = "DELETE_WEBINAR_FAILURE";

export const FETCH_BOOKED_DATES = "FETCH_BOOKED_DATES";
export const FETCH_BOOKED_DATES_SUCCESS = "FETCH_BOOKED_DATES_SUCCESS";
export const FETCH_BOOKED_DATES_FAILURE = "FETCH_BOOKED_DATES_FAILURE";
